baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Decisions & Dragons'
theme = 'dnd'

[markup]
[markup.highlight]
style = "gruvbox"

[menu]

[[menu.nav]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.nav]]
identifier = "notation"
name = "Notation"
url = "/notation/"
weight = 2

[[menu.nav]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 3

[[menu.nav]]
identifier = "corrections"
name = "Corrections"
url = "/corrections/"
weight = 4
